
import React, { useState, useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { 
  FileText, 
  Download, 
  Printer, 
  Share2, 
  Loader2, 
  ChevronRight,
  Sparkles,
  BookOpen,
  Send,
  BrainCircuit,
  MessageCircle,
  CheckCircle2,
  Copy,
  FileDown,
  X,
  Zap,
  Layers,
  FileSearch,
  Target,
  Wand2
} from 'lucide-react';
import { BlueprintResult } from '../types';
import { GeminiService } from '../services/geminiService';
import Logo from './Logo';

interface BlueprintViewProps {
  blueprint: BlueprintResult | null;
  loading: boolean;
  onGenerate: () => void;
  onUpdateBlueprint: (updated: BlueprintResult) => void;
  conceptProvided: boolean;
  previousContext?: string;
}

interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

const BlueprintView: React.FC<BlueprintViewProps> = ({ blueprint, loading, onGenerate, onUpdateBlueprint, conceptProvided, previousContext }) => {
  const [chatInput, setChatInput] = useState('');
  const [isRefining, setIsRefining] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [showShareToast, setShowShareToast] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isRefining]);

  const handleScrollToSection = (e: React.MouseEvent, sectionId: string) => {
    e.preventDefault();
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      window.history.replaceState(null, '', `#${sectionId}`);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    if (!blueprint) return;
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${blueprint.title.replace(/\s+/g, '_')}_Whitepaper_${timestamp}.md`;
    
    let content = `# ${blueprint.title}\n\n`;
    content += `*Generated by Venyro Strategic Architect*\n\n---\n\n`;
    
    blueprint.sections.forEach((section, idx) => {
      content += `## ${idx + 1}. ${section.title}\n\n${section.content}\n\n`;
    });

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    const shareText = `Venyro Venture Blueprint: ${blueprint?.title || 'Synthesis'}\nAccess strategic architecture at ${window.location.href}`;
    try {
      await navigator.clipboard.writeText(shareText);
      setShowShareToast(true);
      setTimeout(() => setShowShareToast(false), 3000);
    } catch (err) {
      console.error('Failed to copy share link', err);
    }
  };

  const handleSendMessage = async (instruction: string) => {
    if (!instruction.trim() || isRefining || !blueprint) return;

    setChatInput('');
    setMessages(prev => [...prev, { role: 'user', text: instruction }]);
    setIsRefining(true);

    try {
      const gemini = new GeminiService();
      const history = messages.map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));
      
      const updatedBlueprint = await gemini.refineBlueprint(blueprint, instruction, history, previousContext);
      onUpdateBlueprint(updatedBlueprint);
      
      setMessages(prev => [...prev, { 
        role: 'model', 
        text: `### Document Refinement Protocol Complete\n\nI have adjusted the whitepaper for **${blueprint.title}** per your instructions. The document structure has been re-synthesized for maximum professional clarity.` 
      }]);
    } catch (error: any) {
      console.error("Refinement error:", error);
      setMessages(prev => [...prev, { 
        role: 'model', 
        text: `### Document Protocol Error\n\n${error.message || "I encountered an error while restructuring the whitepaper."}` 
      }]);
    } finally {
      setIsRefining(false);
    }
  };

  const quickCommands = [
    { label: 'Synthesis', cmd: 'synthesis', icon: Layers },
    { label: 'Expand', cmd: 'expand', icon: Zap },
    { label: 'Summary', cmd: 'summary', icon: FileSearch },
    { label: 'Strategy', cmd: 'strategy', icon: Target },
    { label: 'Refine', cmd: 'refine', icon: Wand2 },
  ];

  const architectSuggestions = [
    "Detail the financial projections",
    "Add a competitive landscape matrix",
    "Expand on technical scalability",
    "Outline the 12-month hiring roadmap",
    "Add a section on Exit Strategy"
  ];

  if (loading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center min-h-[500px] p-8">
        <div className="relative mb-8">
          <Logo isGenerating={true} className="h-20 w-20" hideText />
        </div>
        <h2 className="text-2xl font-semibold text-primary mb-3">Drafting Executive Whitepaper</h2>
        <p className="text-sm text-zinc-500 max-w-sm text-center leading-relaxed">
          The Strategic Architect is meticulously synthesizing a 20-section institutional-grade document. Analyzing technical risks, revenue stability, and market compliance...
        </p>
      </div>
    );
  }

  if (!blueprint) {
    return (
      <div className="max-w-4xl mx-auto p-12 text-center animate-in fade-in slide-in-from-bottom-4 py-20">
        <div className="w-24 h-24 bg-surface/50 border border-border rounded-[2.5rem] flex items-center justify-center mx-auto mb-10 shadow-[0_20px_50px_rgba(0,0,0,0.5)]">
          <BookOpen className="w-10 h-10 text-zinc-500" />
        </div>
        <h1 className="text-4xl lg:text-5xl font-semibold text-primary mb-6 tracking-tight">Executive Whitepaper Architect</h1>
        <p className="text-zinc-500 text-xl max-w-2xl mx-auto mb-12 leading-relaxed font-light">
          Transform your vision into a professional, investor-ready asset. Our analyst engine synthesizes comprehensive whitepapers including technical architecture, tokenomics, and detailed revenue models.
        </p>
        
        {!conceptProvided && (
          <div className="bg-red-500/5 border border-red-500/20 p-5 rounded-2xl text-red-400 text-sm mb-12 max-w-md mx-auto flex items-center gap-3">
            <span className="w-2 h-2 rounded-full bg-red-500 shrink-0"></span>
            Define your core vision in the "New Strategy" tab to initiate architect synthesis.
          </div>
        )}

        <button 
          disabled={!conceptProvided}
          onClick={onGenerate}
          className="bg-primary text-background px-10 py-4 rounded-[1.5rem] font-bold text-sm hover:bg-white transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-4 mx-auto shadow-2xl shadow-white/5 active:scale-95 transform"
        >
          <Sparkles className="w-5 h-5" />
          Synthesize Full Whitepaper
        </button>
      </div>
    );
  }

  return (
    <div ref={scrollContainerRef} className="flex-1 overflow-y-auto scroll-smooth animate-in fade-in duration-500">
      <div className="sticky top-0 z-30 bg-background/80 backdrop-blur-2xl border-b border-border/50 px-8 py-6 print:hidden">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="min-w-0">
            <div className="flex items-center gap-2 mb-2">
               <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
               <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-zinc-500">VC-Compliant Whitepaper Output</span>
            </div>
            <h1 className="text-2xl font-bold text-primary truncate max-w-xl">{blueprint.title}</h1>
          </div>
          <div className="flex items-center gap-3 shrink-0">
            <button 
              onClick={handleDownloadMarkdown}
              title="Download Markdown Source"
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-surface border border-border text-zinc-400 hover:text-primary text-xs font-medium transition-all"
            >
              <FileDown className="w-3.5 h-3.5" /> MD
            </button>
            <button 
              onClick={handlePrint}
              title="Print to PDF"
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-surface border border-border text-zinc-400 hover:text-primary text-xs font-medium transition-all"
            >
              <Printer className="w-3.5 h-3.5" /> PDF
            </button>
            <div className="relative">
              <button 
                onClick={handleShare}
                className="flex items-center gap-2 px-6 py-2 rounded-xl bg-primary text-background font-bold text-xs hover:bg-white transition-all shadow-lg shadow-white/5 active:scale-95"
              >
                <Share2 className="w-3.5 h-3.5" /> Share
              </button>
              {showShareToast && (
                <div className="absolute top-full mt-3 right-0 bg-emerald-500 text-white text-[10px] py-2 px-4 rounded-lg font-bold uppercase tracking-widest flex items-center gap-2 shadow-2xl animate-in zoom-in duration-200">
                  <CheckCircle2 className="w-3 h-3" /> Copied
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-8 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16">
          <div className="lg:col-span-3 print:hidden">
            <div className="sticky top-32 space-y-6">
              <div className="px-4 py-2 rounded-xl bg-zinc-900/50 border border-border">
                <h3 className="text-[10px] uppercase font-bold text-zinc-500 tracking-[0.2em] mb-4 mt-2">Document Structure</h3>
                <nav className="space-y-1 pb-2">
                  {blueprint.sections.map((section, idx) => (
                    <a 
                      key={idx} 
                      href={`#section-${idx}`}
                      onClick={(e) => handleScrollToSection(e, `section-${idx}`)}
                      className="group flex items-center justify-between p-2.5 rounded-lg hover:bg-surface/50 text-zinc-500 hover:text-primary transition-all border border-transparent hover:border-border"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <span className="text-[10px] font-mono text-zinc-700">{idx + 1 < 10 ? `0${idx + 1}` : idx + 1}</span>
                        <span className="text-xs font-medium truncate">{section.title}</span>
                      </div>
                      <ChevronRight className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity" />
                    </a>
                  ))}
                </nav>
              </div>
              <div className="p-6 rounded-3xl bg-surface/20 border border-border/50 text-center">
                 <p className="text-[10px] text-zinc-600 leading-relaxed font-medium">This document is architectural-grade. Verified for completeness, technical viability, and professional tone.</p>
              </div>
            </div>
          </div>

          <div className="lg:col-span-9 space-y-24 pb-40 print:col-span-12">
            {blueprint.sections.map((section, idx) => (
              <section key={idx} id={`section-${idx}`} className="scroll-mt-36 space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-700" style={{ animationDelay: `${idx * 100}ms` }}>
                <div className="flex items-center gap-6">
                  <div className="text-4xl font-light text-zinc-800 font-mono">{idx + 1 < 10 ? `0${idx + 1}` : idx + 1}</div>
                  <h2 className="text-2xl font-semibold text-primary tracking-tight">{section.title}</h2>
                  <div className="flex-1 h-px bg-zinc-900 print:hidden"></div>
                </div>
                <div className="prose-custom max-w-none">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{section.content}</ReactMarkdown>
                </div>
              </section>
            ))}
            
            <div className="pt-12 border-t border-zinc-900 flex items-center justify-between print:hidden">
               <div className="flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-emerald-900"></div>
                  <p className="text-[10px] text-zinc-600 font-mono tracking-widest uppercase">End of Institutional Whitepaper Asset</p>
               </div>
               <button onClick={() => scrollContainerRef.current?.scrollTo({ top: 0, behavior: 'smooth' })} className="text-[10px] font-bold text-zinc-500 hover:text-white transition-colors uppercase tracking-widest">
                  Back to Top
               </button>
            </div>

            <div className="mt-32 space-y-8 animate-in slide-up duration-1000 print:hidden">
               <div className="flex items-center gap-4">
                 <div className="w-12 h-12 rounded-[1.2rem] bg-zinc-900 border border-border flex items-center justify-center shadow-xl">
                   <BrainCircuit className="w-6 h-6 text-primary" />
                 </div>
                 <div>
                   <h3 className="text-xs font-bold text-primary uppercase tracking-[0.2em]">Document Refinement Studio</h3>
                   <p className="text-[10px] text-zinc-500 font-medium">Collaborate with the analyst to polish specific whitepaper sections.</p>
                 </div>
               </div>

               <div className="rounded-[2.5rem] bg-zinc-950/40 border border-border/80 backdrop-blur-xl overflow-hidden shadow-2xl flex flex-col min-h-[400px]">
                  <div className="flex-1 overflow-y-auto p-8 space-y-8 max-h-[500px] scrollbar-hide">
                    {messages.length === 0 && (
                      <div className="h-full flex flex-col items-center justify-center text-center opacity-40 py-20 space-y-6">
                        <MessageCircle className="w-12 h-12 text-zinc-600" />
                        <div className="space-y-1">
                          <p className="text-sm font-medium text-zinc-400">Collaborative Refinement Active</p>
                          <p className="text-[11px] text-zinc-600 max-w-[280px] mx-auto leading-relaxed">Try: "Elaborate on the Tokenomics with a lock-up schedule" or "Refine the roadmap for institutional compliance."</p>
                        </div>
                      </div>
                    )}
                    {messages.map((msg, idx) => (
                      <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-in fade-in slide-in-from-bottom-2`}>
                        <div className={`max-w-[85%] rounded-[1.8rem] px-6 py-4 shadow-xl ${
                          msg.role === 'user' 
                            ? 'bg-primary text-background font-bold text-xs' 
                            : 'bg-surface/60 border border-border text-zinc-300 text-sm'
                        }`}>
                          {msg.role === 'user' ? (
                            msg.text
                          ) : (
                            <div className="prose-custom prose-sm max-w-none">
                              <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.text}</ReactMarkdown>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                    {isRefining && (
                      <div className="flex justify-start animate-in fade-in">
                        <div className="bg-surface/40 border border-border rounded-full px-6 py-3 flex items-center gap-4">
                          <Logo isGenerating={true} className="h-4 w-4" hideText />
                          <span className="text-[10px] text-zinc-500 font-bold uppercase tracking-widest italic">Analyzing and updating sections...</span>
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>

                  <div className="px-6 py-3 border-t border-white/5 bg-zinc-900/50 flex items-center gap-4 overflow-x-auto no-scrollbar">
                     <span className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest whitespace-nowrap">Analyst Tools:</span>
                     {quickCommands.map((item) => (
                       <button
                         key={item.cmd}
                         onClick={() => handleSendMessage(item.cmd)}
                         disabled={isRefining}
                         className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-border bg-zinc-950 text-zinc-500 hover:text-primary hover:border-zinc-500 transition-all active:scale-95 group shrink-0"
                       >
                         <item.icon className="w-3 h-3 group-hover:scale-110 transition-transform" />
                         <span className="text-[10px] font-bold uppercase tracking-wider">{item.label}</span>
                       </button>
                     ))}
                  </div>

                  <div className="p-6 bg-black/40 border-t border-border/50 space-y-4">
                    <div className="flex flex-wrap gap-2">
                       {architectSuggestions.map((suggestion) => (
                         <button
                           key={suggestion}
                           onClick={() => handleSendMessage(suggestion)}
                           disabled={isRefining}
                           className="px-3 py-1.5 rounded-lg bg-zinc-900 border border-border text-[10px] font-medium text-zinc-500 hover:text-primary hover:border-zinc-500 transition-all active:scale-95"
                         >
                           + {suggestion}
                         </button>
                       ))}
                    </div>
                    <form 
                      onSubmit={(e) => {
                        e.preventDefault();
                        handleSendMessage(chatInput);
                      }} 
                      className="flex items-center gap-4"
                    >
                      <input 
                        type="text" 
                        value={chatInput}
                        onChange={(e) => setChatInput(e.target.value)}
                        placeholder="Instruct the whitepaper writer..." 
                        className="flex-1 bg-transparent border-none outline-none text-sm text-zinc-300 placeholder:text-zinc-700 py-3 px-2"
                      />
                      <button 
                        type="submit"
                        disabled={!chatInput.trim() || isRefining}
                        className="w-12 h-12 rounded-2xl bg-primary text-background flex items-center justify-center hover:scale-110 active:scale-90 transition-all disabled:opacity-30 disabled:grayscale shadow-xl"
                      >
                         <Logo isGenerating={isRefining} className="h-5 w-5" hideText />
                      </button>
                    </form>
                  </div>
               </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BlueprintView;
